name: Build and Deploy the master branch

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 📣 Deprecation notice
        run: echo "We will most likely run integration tests only with security so this build will be removed."
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Set up JDK 15 and Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
          server-id: sonatype-nexus-snapshots
          server-username: MAVEN_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
      - name: Docker Layer Caching
        uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
        with:
          key: fscrawler-docker-cache-{hash}
          restore-keys: |
            fscrawler-docker-cache-
      - name: Build the project
        run: mvn --batch-mode install -DskipTests -Ddocker.skip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Set up JDK 15 and Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
          server-id: sonatype-nexus-snapshots
          server-username: MAVEN_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
      - name: Docker Layer Caching
        uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
        with:
          key: fscrawler-docker-cache-{hash}
          restore-keys: |
            fscrawler-docker-cache-
      - name: Deploy with Maven
        run: mvn deploy -DskipTests
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

#  build-security:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up JDK 15
#        uses: actions/setup-java@v2
#        with:
#          java-version: '15'
#          distribution: 'adopt'
#      - name: Cache Maven packages
#        uses: actions/cache@v2
#        with:
#          path: ~/.m2
#          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
#          restore-keys: ${{ runner.os }}-m2
#      - name: Build the project and run tests with security
#        run: mvn --batch-mode verify -Psecurity -DskipTests
